import type { SupabaseClient } from '@supabase/supabase-js'
import type { SearchRelationship } from '../../../../shared/search/contracts.js'
import type { SearchIndexMetadata, SearchPermissionSimulationAudit, SearchProjection, SearchProjectionRepository, SearchRefreshFailure, SearchRefreshRun } from '../../../../shared/search/persistence.js'

export class SupabaseSearchProjectionRepository implements SearchProjectionRepository {
  private readonly client: SupabaseClient
  constructor(client: SupabaseClient) { this.client = client }

  async listProjections(filter: { dataset?: string; recordIds?: readonly string[] } = {}): Promise<readonly SearchProjection[]> {
    let query = this.client.from('search_projections').select('*')
    if (filter.dataset) query = query.eq('source_dataset', filter.dataset)
    if (filter.recordIds?.length) query = query.in('source_record_id', [...filter.recordIds])
    const { data, error } = await query.order('projection_id')
    if (error) throw new Error(`Unable to list search projections: ${error.message}`)
    return (data ?? []) as SearchProjection[]
  }
  async getProjection(projectionId: string): Promise<SearchProjection | undefined> { const { data, error } = await this.client.from('search_projections').select('*').eq('projection_id', projectionId).maybeSingle(); if (error) throw new Error(`Unable to load search projection: ${error.message}`); return data as SearchProjection | undefined }
  async upsertProjection(projection: SearchProjection): Promise<'inserted' | 'updated' | 'unchanged'> { const existing = await this.getProjection(projection.projection_id); if (existing?.content_hash === projection.content_hash) return 'unchanged'; const { error } = await this.client.from('search_projections').upsert(toProjectionRow(projection), { onConflict: 'projection_id' }); if (error) throw new Error(`Unable to upsert search projection: ${error.message}`); return existing ? 'updated' : 'inserted' }
  async bulkUpsertProjections(projections: readonly SearchProjection[]) { const counts = { inserted: 0, updated: 0, unchanged: 0 }; for (const projection of projections) counts[await this.upsertProjection(projection)]++; return counts }
  async deleteProjection(projectionId: string): Promise<boolean> { const { error, count } = await this.client.from('search_projections').delete({ count: 'exact' }).eq('projection_id', projectionId); if (error) throw new Error(`Unable to delete search projection: ${error.message}`); return (count ?? 0) > 0 }
  async deleteBySource(dataset: string, recordIds?: readonly string[]): Promise<number> { let query = this.client.from('search_projections').delete({ count: 'exact' }).eq('source_dataset', dataset); if (recordIds?.length) query = query.in('source_record_id', [...recordIds]); const { error, count } = await query; if (error) throw new Error(`Unable to delete search projections: ${error.message}`); return count ?? 0 }
  async listRelationships(sourceProjectionId?: string) { let query = this.client.from('search_relationship_projections').select('*'); if (sourceProjectionId) query = query.eq('source_projection_id', sourceProjectionId); const { data, error } = await query; if (error) throw new Error(`Unable to list search relationships: ${error.message}`); return (data ?? []).map((row) => ({ source_projection_id: String(row.source_projection_id), relationship: { type: String(row.relationship_type), targetDataset: String(row.target_dataset), targetId: String(row.target_record_id), weight: typeof row.weight === 'number' ? row.weight : undefined, label: typeof row.label === 'string' ? row.label : undefined } as SearchRelationship })) }
  async replaceRelationships(sourceProjectionId: string, relationships: readonly SearchRelationship[]) { const previous = await this.listRelationships(sourceProjectionId); const { error: deleteError } = await this.client.from('search_relationship_projections').delete().eq('source_projection_id', sourceProjectionId); if (deleteError) throw new Error(`Unable to replace search relationships: ${deleteError.message}`); if (relationships.length) { const { error } = await this.client.from('search_relationship_projections').insert(relationships.map((relationship) => ({ source_projection_id: sourceProjectionId, relationship_type: relationship.type, target_dataset: relationship.targetDataset, target_record_id: relationship.targetId, weight: relationship.weight ?? null, label: relationship.label ?? null }))); if (error) throw new Error(`Unable to insert search relationships: ${error.message}`) } return { inserted: relationships.length, removed: previous.length } }
  async readIndexMetadata(): Promise<SearchIndexMetadata> { const { data, error } = await this.client.from('search_index_metadata').select('*').eq('id', 1).maybeSingle(); if (error) throw new Error(`Unable to load search index metadata: ${error.message}`); return (data ?? defaultMetadata()) as SearchIndexMetadata }
  async updateIndexMetadata(metadata: SearchIndexMetadata): Promise<void> { const { error } = await this.client.from('search_index_metadata').upsert({ id: 1, ...metadata, provider_versions: metadata.provider_versions }, { onConflict: 'id' }); if (error) throw new Error(`Unable to update search index metadata: ${error.message}`) }
  async recordRefreshRun(run: SearchRefreshRun): Promise<void> { const { error } = await this.client.from('search_refresh_runs').insert({ run_id: run.run_id, mode: run.mode, datasets_requested: run.datasets_requested, records_inspected: run.records_inspected, records_inserted: run.records_inserted, records_updated: run.records_updated, records_unchanged: run.records_unchanged, records_removed: run.records_removed, relationships_inserted: run.relationships_inserted, relationships_removed: run.relationships_removed, failures: run.failures, started_at: run.started_at, finished_at: run.finished_at, duration_ms: run.duration_ms, resulting_index_version: run.resulting_index_version }); if (error) throw new Error(`Unable to record search refresh run: ${error.message}`) }
  async recordRefreshError(error: SearchRefreshFailure, occurredAt: string): Promise<void> { const { error: insertError } = await this.client.from('search_refresh_errors').insert({ dataset: error.dataset, record_id: error.record_id ?? null, code: error.code, message: error.message, occurred_at: occurredAt }); if (insertError) throw new Error(`Unable to record search refresh error: ${insertError.message}`) }
  async recordPermissionSimulation(audit: SearchPermissionSimulationAudit): Promise<void> { const { error } = await this.client.from('search_permission_simulations').insert({ real_actor_id: audit.real_actor_id, simulated_role: audit.simulated_role, simulated_permissions: audit.simulated_permissions, occurred_at: audit.occurred_at }); if (error) throw new Error(`Unable to record Search permission simulation: ${error.message}`) }
}

function toProjectionRow(projection: SearchProjection): Record<string, unknown> { const { relationships: _relationships, ...row } = projection; return { ...row, keywords: [...projection.keywords], tags: [...projection.tags] } }
function defaultMetadata(): SearchIndexMetadata { return { index_version: 0, projection_count: 0, relationship_count: 0, last_successful_refresh: null, last_failed_refresh: null, cache_built_at: null, schema_version: 1, provider_versions: {}, stale: true } }

