import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { supabase } from '../../lib/supabase'
import { track } from '../../platform/analytics/analytics'

type Report = { dailyUsers: number; weeklyUsers: number; monthlyUsers: number; mostViewedPages: Array<{ label: string; value: number }>; devices: Array<{ label: string; value: number }>; browsers: Array<{ label: string; value: number }>; trafficSources: Array<{ label: string; value: number }>; search: { total: number; zeroResults: number; averageQueryLength: number }; eventCounts: Record<string, number>; errors: Array<{ event_name: string; occurred_at: string; properties: Record<string, unknown> }>; recentPublication: Array<{ event_name: string; occurred_at: string }> }

function Breakdown({ title, items }: { title: string; items: Array<{ label: string; value: number }> }) {
  return <section className="analytics-panel"><h2>{title}</h2>{items.length ? <ul className="analytics-breakdown">{items.map((item) => <li key={item.label}><span>{item.label}</span><strong>{item.value}</strong></li>)}</ul> : <p>No events recorded yet.</p>}</section>
}

export function AnalyticsPage() {
  const [report, setReport] = useState<Report | null>(null)
  const [error, setError] = useState('')
  useEffect(() => { track('page_view', { route: '/admin/analytics' }); void supabase.auth.getSession().then(async ({ data }) => { const response = await fetch('/api/analytics', { headers: { Authorization: `Bearer ${data.session?.access_token ?? ''}` } }); const body = await response.json() as { data?: Report; message?: string }; if (!response.ok) throw new Error(body.message ?? 'Analytics unavailable.'); setReport(body.data ?? null) }).catch((value: unknown) => setError(value instanceof Error ? value.message : 'Analytics unavailable.')) }, [])
  return <main className="admin-page analytics-page"><header className="admin-dashboard-hero"><div><p className="admin-page__eyebrow">Forge Admin · Analytics</p><h1>Production observability</h1><p className="admin-page__intro">Anonymous product usage, operational signals and failure insight for the last 30 days.</p></div><Link to="/admin" className="button button--secondary">Admin home</Link></header>{error && <div className="error-state" role="alert">{error}</div>}{!report && !error && <p role="status">Loading analytics…</p>}{report && <><nav className="analytics-tabs" aria-label="Analytics sections">{['Overview','Users','Search','Content','Performance','Errors','Operations'].map((tab) => <a href={`#analytics-${tab.toLowerCase()}`} key={tab}>{tab}</a>)}</nav><section id="analytics-overview" className="admin-dashboard-stats"><article><span>Daily users</span><strong>{report.dailyUsers}</strong></article><article><span>Weekly users</span><strong>{report.weeklyUsers}</strong></article><article><span>Monthly users</span><strong>{report.monthlyUsers}</strong></article><article><span>Searches</span><strong>{report.search.total}</strong></article></section><div className="analytics-grid"><div id="analytics-users"><Breakdown title="Most viewed pages" items={report.mostViewedPages} /><Breakdown title="Devices" items={report.devices} /></div><div id="analytics-search"><section className="analytics-panel"><h2>Search intelligence</h2><dl><div><dt>Zero-result searches</dt><dd>{report.search.zeroResults}</dd></div><div><dt>Average query length</dt><dd>{report.search.averageQueryLength} characters</dd></div></dl></section><Breakdown title="Traffic sources" items={report.trafficSources} /></div><div id="analytics-content"><section className="analytics-panel"><h2>Feature activity</h2><ul className="analytics-breakdown">{Object.entries(report.eventCounts).filter(([, value]) => value > 0).slice(0, 15).map(([label, value]) => <li key={label}><span>{label.replaceAll('_', ' ')}</span><strong>{value}</strong></li>)}</ul></section></div><div id="analytics-performance"><Breakdown title="Browsers" items={report.browsers} /></div><div id="analytics-errors"><section className="analytics-panel"><h2>Recent errors</h2>{report.errors.length ? <ul>{report.errors.map((item, index) => <li key={`${item.occurred_at}-${index}`}>{item.event_name} · {new Date(item.occurred_at).toLocaleString()}</li>)}</ul> : <p>No JavaScript or API errors recorded.</p>}</section></div><div id="analytics-operations"><section className="analytics-panel"><h2>Publication activity</h2>{report.recentPublication.length ? <ul>{report.recentPublication.map((item, index) => <li key={`${item.occurred_at}-${index}`}>{item.event_name.replaceAll('_', ' ')} · {new Date(item.occurred_at).toLocaleString()}</li>)}</ul> : <p>No publication activity recorded.</p>}</section></div></div></>}</main>
}
