import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { KingshotArtRenderer } from '../../components/art/KingshotArtRenderer'
import { analyseArtworkDetailed, cloneCalibration, DEFAULT_CALIBRATION, DEVICE_PROFILES, getBenchmarkArtwork, getBenchmarkAvailability, isSavedCalibrationProfile, loadCalibrationProfiles, makeCalibrationProfile, persistCalibrationProfiles, RENDER_BENCHMARKS, resolveDeviceProfile } from '../../render-engine'
import type { CalibrationConfiguration, DeviceProfile, DeviceProfileId, DeviceProfileOverrides, GlyphCalibration, GlyphFamily, SavedCalibrationProfile } from '../../render-engine'
import { analyseText, repairText, RENDER_PROFILES, type RenderProfile } from '../../../shared/domains/art-studio/rendering'
import { CANONICAL_RENDER_FIXTURES, getCanonicalFixture } from '../../render-engine/fixtures'
import './renderEngineCalibration.css'

const FAMILIES: GlyphFamily[] = ['space', 'ascii', 'box-drawing', 'unicode', 'emoji', 'pixel-circles', 'hearts', 'decorative-symbols']
function getStorage(): Storage | undefined { try { return typeof window === 'undefined' ? undefined : window.localStorage } catch { return undefined } }
const STORAGE = getStorage()
const familyLabel = (family: GlyphFamily) => family.replaceAll('-', ' ')
const copy = <T,>(value: T): T => structuredClone(value)
const serialiseDraft = (calibration: CalibrationConfiguration, overrides: DeviceProfileOverrides, device: DeviceProfileId, benchmarkId: string) => JSON.stringify({ calibration, overrides, device, benchmarkId })

type Pan = { x: number; y: number }
type ComparisonMode = 'side-by-side' | 'overlay' | 'reference-only' | 'forge-only' | 'difference'

function ZoomPanViewport({ children, zoom, pan, setZoom, setPan, label, className = '' }: { children: ReactNode; zoom: number; pan: Pan; setZoom: (value: number | ((current: number) => number)) => void; setPan: (value: Pan) => void; label: string; className?: string }) {
  const drag = useRef<{ x: number; y: number; pan: Pan } | undefined>(undefined)
  function wheel(event: React.WheelEvent<HTMLDivElement>) { event.preventDefault(); setZoom((current) => Math.min(3, Math.max(.25, Number((current + (event.deltaY < 0 ? .1 : -.1)).toFixed(2))))) }
  return <div className={`render-engine-lab__viewport ${className}`} aria-label={label} onWheel={wheel} onPointerDown={(event) => { event.currentTarget.setPointerCapture(event.pointerId); drag.current = { x: event.clientX, y: event.clientY, pan } }} onPointerMove={(event) => { if (!drag.current) return; setPan({ x: drag.current.pan.x + event.clientX - drag.current.x, y: drag.current.pan.y + event.clientY - drag.current.y }) }} onPointerUp={() => { drag.current = undefined }} onPointerCancel={() => { drag.current = undefined }}>
    <div className="render-engine-lab__zoom-content" style={{ transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom})` }}>{children}</div>
    <div className="render-engine-lab__zoom-controls" role="group" aria-label={`${label} zoom controls`}><button type="button" onClick={() => setZoom((current) => Math.min(3, Number((current + .1).toFixed(2))))} aria-label="Zoom in">+</button><output>{Math.round(zoom * 100)}%</output><button type="button" onClick={() => setZoom((current) => Math.max(.25, Number((current - .1).toFixed(2))))} aria-label="Zoom out">−</button><button type="button" onClick={() => { setZoom(1); setPan({ x: 0, y: 0 }) }}>Fit / 100%</button></div>
  </div>
}

export function RenderEngineCalibrationPage() {
  const [fixtureId, setFixtureId] = useState(CANONICAL_RENDER_FIXTURES[0].id)
  const [benchmarkId, setBenchmarkId] = useState(RENDER_BENCHMARKS[0].id)
  const [deviceId, setDeviceId] = useState<DeviceProfileId>('android-default')
  const [family, setFamily] = useState<GlyphFamily>('pixel-circles')
  const [calibration, setCalibration] = useState<CalibrationConfiguration>(() => cloneCalibration(DEFAULT_CALIBRATION))
  const [deviceOverrides, setDeviceOverrides] = useState<DeviceProfileOverrides>({})
  const [profiles, setProfiles] = useState<SavedCalibrationProfile[]>(() => loadCalibrationProfiles(STORAGE))
  const [activeProfileId, setActiveProfileId] = useState<string>()
  const [lastSavedAt, setLastSavedAt] = useState<string>()
  const [status, setStatus] = useState('Unsaved changes')
  const [renderMode, setRenderMode] = useState<'artwork-only' | 'chat-simulation'>('chat-simulation')
  const [comparisonMode, setComparisonMode] = useState<ComparisonMode>('side-by-side')
  const [referenceUrl, setReferenceUrl] = useState<string | undefined>(CANONICAL_RENDER_FIXTURES[0].screenshots.chat)
  const [referenceName, setReferenceName] = useState<string | undefined>('Kingshot chat reference')
  const [referenceZoom, setReferenceZoom] = useState(1)
  const [referencePan, setReferencePan] = useState<Pan>({ x: 0, y: 0 })
  const [referenceAlignment, setReferenceAlignment] = useState({ x: 0, y: 0, scale: 1, rotation: 0, opacity: .5 })
  const [forgeZoom, setForgeZoom] = useState(1)
  const [forgePan, setForgePan] = useState<Pan>({ x: 0, y: 0 })
  const [showGrid, setShowGrid] = useState(false)
  const [showGuides, setShowGuides] = useState(false)
  const [background, setBackground] = useState<'dark' | 'light' | 'checker'>('dark')
  const [focusPreview, setFocusPreview] = useState(false)
  const [importKey, setImportKey] = useState(0)
  const [sourceText, setSourceText] = useState('')
  const [textProfileId, setTextProfileId] = useState('kingshot-chat')
  const fixture = getCanonicalFixture(fixtureId)
  const previousBenchmark = useRef(benchmarkId)
  const benchmark = RENDER_BENCHMARKS.find((item) => item.id === benchmarkId) ?? RENDER_BENCHMARKS[0]
  const benchmarkArtwork = getBenchmarkArtwork(benchmark)
  const artwork = sourceText || fixture.text || benchmarkArtwork
  const analysis = useMemo(() => analyseArtworkDetailed(artwork), [artwork])
  const textProfile: RenderProfile = RENDER_PROFILES[textProfileId] ?? RENDER_PROFILES['kingshot-chat']
  const textDiagnostics = useMemo(() => analyseText(artwork, textProfile), [artwork, textProfile])
  const familyCount = analysis.familyCounts[family]
  const deviceProfile = useMemo(() => resolveDeviceProfile(deviceId, deviceOverrides), [deviceId, deviceOverrides])
  const activeProfile = profiles.find((profile) => profile.id === activeProfileId)
  const savedDraft = activeProfile ? serialiseDraft(activeProfile.calibration, activeProfile.deviceOverrides, activeProfile.baseDeviceProfile, activeProfile.benchmarkId ?? '') : serialiseDraft(DEFAULT_CALIBRATION, {}, deviceId, benchmarkId)
  const currentDraft = serialiseDraft(calibration, deviceOverrides, deviceId, benchmarkId)
  const dirty = currentDraft !== savedDraft
  const hasCalibrationChanges = JSON.stringify(calibration) !== JSON.stringify(DEFAULT_CALIBRATION)
  const familyChanged = JSON.stringify(calibration[family]) !== JSON.stringify(DEFAULT_CALIBRATION[family])
  const hasDeviceChanges = Object.keys(deviceOverrides).length > 0
  const hasWorkingChanges = dirty || hasCalibrationChanges || hasDeviceChanges

  useEffect(() => { setStatus(dirty ? 'Unsaved changes' : activeProfile ? 'Saved locally' : 'Defaults loaded') }, [activeProfile, dirty])
  useEffect(() => { if (previousBenchmark.current === benchmarkId) return; previousBenchmark.current = benchmarkId; if (!artwork) return; const significant = FAMILIES.filter((item) => item !== 'space').sort((a, b) => analysis.familyCounts[b] - analysis.familyCounts[a])[0]; if (significant && analysis.familyCounts[significant] > 0) setFamily(significant) }, [analysis, artwork, benchmarkId])
  useEffect(() => () => { if (referenceUrl) URL.revokeObjectURL(referenceUrl) }, [referenceUrl])

  function confirmDiscard(message = 'Discard unsaved calibration changes?') { return !dirty || window.confirm(message) }
  function persist(profilesToSave: SavedCalibrationProfile[]) { try { persistCalibrationProfiles(profilesToSave, STORAGE); setProfiles(profilesToSave); setStatus('Saved locally') } catch { setStatus('Could not save locally') } }
  function applyProfile(profile: SavedCalibrationProfile) { setCalibration(cloneCalibration(profile.calibration)); setDeviceOverrides(copy(profile.deviceOverrides)); setDeviceId(profile.baseDeviceProfile); if (profile.benchmarkId) setBenchmarkId(profile.benchmarkId); setActiveProfileId(profile.id); setLastSavedAt(profile.updatedAt); setStatus('Saved locally') }
  function saveAs(name?: string) { const profile = makeCalibrationProfile({ name: name ?? window.prompt('Name this calibration profile', `${benchmark.title} Calibration`) ?? '', baseDeviceProfile: deviceId, calibration, deviceOverrides, benchmarkId }); if (!profile.name) return; persist([...profiles, profile]); setActiveProfileId(profile.id); setLastSavedAt(profile.updatedAt) }
  function save() { if (activeProfile) { const updated = { ...activeProfile, updatedAt: new Date().toISOString(), baseDeviceProfile: deviceId, calibration: cloneCalibration(calibration), deviceOverrides: copy(deviceOverrides), benchmarkId }; persist(profiles.map((profile) => profile.id === activeProfile.id ? updated : profile)); setLastSavedAt(updated.updatedAt) } else saveAs() }
  function renameProfile() { if (!activeProfile) return; const name = window.prompt('Rename saved profile', activeProfile.name)?.trim(); if (!name) return; persist(profiles.map((profile) => profile.id === activeProfile.id ? { ...profile, name, updatedAt: new Date().toISOString() } : profile)) }
  function duplicateProfile() { if (!activeProfile) return; saveAs(`${activeProfile.name} Copy`) }
  function loadProfile(profile: SavedCalibrationProfile) { if (confirmDiscard('Load this profile and discard current unsaved changes?')) applyProfile(profile) }
  function deleteProfile() { if (!activeProfile || !window.confirm(`Delete “${activeProfile.name}” from this browser?`)) return; persist(profiles.filter((profile) => profile.id !== activeProfile.id)); setActiveProfileId(undefined); setLastSavedAt(undefined); setCalibration(cloneCalibration(DEFAULT_CALIBRATION)); setDeviceOverrides({}) }
  function resetFamily() { setCalibration((current) => ({ ...current, [family]: { ...DEFAULT_CALIBRATION[family] } })) }
  function resetAllCalibration() { setCalibration(cloneCalibration(DEFAULT_CALIBRATION)) }
  function resetDeviceOverrides() { setDeviceOverrides({}) }
  function resetSession() { if (!window.confirm('Reset this working session? Saved profiles will not be deleted.')) return; setCalibration(cloneCalibration(DEFAULT_CALIBRATION)); setDeviceOverrides({}); setActiveProfileId(undefined); setLastSavedAt(undefined) }
  function updateCalibration(field: keyof GlyphCalibration, value: string) { setCalibration((current) => ({ ...current, [family]: { ...current[family], [field]: field === 'fontFamily' ? value : Number(value) } })) }
  function updateDevice(field: keyof DeviceProfile, value: string) { setDeviceOverrides((current) => ({ ...current, [deviceId]: { ...current[deviceId], [field]: Number(value) } })) }
  function selectBenchmark(value: string) { if (value !== benchmarkId && confirmDiscard()) setBenchmarkId(value) }
  function selectFixture(value: string) { if (value === fixtureId || !confirmDiscard()) return; const next = getCanonicalFixture(value); setFixtureId(value); setSourceText(next.text); setReferenceUrl(next.screenshots.chat); setReferenceName('Kingshot chat reference'); setReferencePan({ x: 0, y: 0 }); setReferenceZoom(1) }
  function selectDevice(value: DeviceProfileId) { if (value !== deviceId && confirmDiscard()) setDeviceId(value) }
  function selectReference(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; if (referenceUrl) URL.revokeObjectURL(referenceUrl); setReferenceUrl(URL.createObjectURL(file)); setReferenceName(file.name); setReferencePan({ x: 0, y: 0 }); setReferenceZoom(1) }
  function removeReference() { if (referenceUrl) URL.revokeObjectURL(referenceUrl); setReferenceUrl(undefined); setReferenceName(undefined); setImportKey((key) => key + 1) }
  function resetAlignment() { setReferenceAlignment({ x: 0, y: 0, scale: 1, rotation: 0, opacity: .5 }) }
  function exportProfile() { const profile = makeCalibrationProfile({ name: activeProfile?.name ?? `${benchmark.title} Calibration`, baseDeviceProfile: deviceId, calibration, deviceOverrides, benchmarkId }); const blob = new Blob([JSON.stringify(profile, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${profile.name.toLowerCase().replaceAll(/[^a-z0-9]+/g, '-')}.json`; anchor.click(); URL.revokeObjectURL(url) }
  async function importProfile(event: React.ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; try { const parsed: unknown = JSON.parse(await file.text()); if (!isSavedCalibrationProfile(parsed)) throw new Error('unsupported'); const imported = makeCalibrationProfile({ name: `${parsed.name} Import`, baseDeviceProfile: parsed.baseDeviceProfile, calibration: parsed.calibration, deviceOverrides: parsed.deviceOverrides, benchmarkId: parsed.benchmarkId }); persist([...profiles, imported]); applyProfile(imported); setStatus('Imported and saved locally') } catch { setStatus('Import rejected: invalid calibration profile') } finally { setImportKey((key) => key + 1) } }
  function updateAlignment(field: keyof typeof referenceAlignment, value: string) { setReferenceAlignment((current) => ({ ...current, [field]: Number(value) })) }
  function applySafeTextRepair() { const repaired = repairText(artwork, textProfile); setSourceText(repaired.text); setStatus(`${repaired.operations.length} safe repair${repaired.operations.length === 1 ? '' : 's'} previewed`) }

  const previewClasses = [`render-engine-lab__preview-surface--${background}`, showGrid ? 'render-engine-lab__preview-surface--grid' : '', showGuides ? 'render-engine-lab__preview-surface--guides' : ''].filter(Boolean).join(' ')
  const workspaceClasses = `render-engine-lab__workspace render-engine-lab__workspace--${comparisonMode} ${focusPreview ? 'render-engine-lab__workspace--focus' : ''}`
  const calibrationControlsDisabled = !artwork || familyCount === 0
  const benchmarkAvailability = getBenchmarkAvailability(benchmark)

  return <main className={`admin-page render-engine-lab ${focusPreview ? 'render-engine-lab--focus' : ''}`}>
    <section className="render-engine-lab__panel"><label>Canonical fixture<select value={fixtureId} onChange={(event) => selectFixture(event.target.value)}>{CANONICAL_RENDER_FIXTURES.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><p>{fixture.metadata.notes}</p><p>Reference captures: chat and game loaded from the committed fixture.</p></section>
    <section className="render-engine-lab__guide" aria-labelledby="render-engine-guide-title"><h2 id="render-engine-guide-title">Render Engine workflow</h2><ol><li>Select a benchmark.</li><li>Choose a device profile.</li><li>Pick a glyph family.</li><li>Adjust calibration.</li><li>Set overrides.</li><li>Upload artwork.</li><li>Use overlay mode.</li><li>Save or export.</li><li>Reset the session.</li></ol><p><strong>Legend:</strong> Ready = approved artwork · Metadata only = awaiting artwork · Broken reference = repair required. Current benchmark: {benchmarkAvailability}.</p></section>
    <section className="render-engine-lab__topbar"><div><p className="render-engine-lab__eyebrow">Forge Render Engine / Sprint 9.3</p><h1>Calibration Lab</h1><p>Browser-local visual calibration. No values or screenshots leave this session.</p></div><div className="render-engine-lab__actions"><span className={dirty ? 'render-engine-lab__save-state render-engine-lab__save-state--dirty' : 'render-engine-lab__save-state'}>{status}{lastSavedAt && !dirty && ` · ${new Date(lastSavedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`}</span><button className="button button--primary" type="button" onClick={save}>Save calibration</button><button className="button button--secondary" type="button" onClick={() => saveAs()}>Save as new</button></div></section>
    <section className="render-engine-lab__toolbar"><label>Benchmark<select value={benchmarkId} onChange={(event) => selectBenchmark(event.target.value)}>{RENDER_BENCHMARKS.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label>Text profile<select value={textProfileId} onChange={(event) => setTextProfileId(event.target.value)}>{Object.values(RENDER_PROFILES).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Device profile<select value={deviceId} onChange={(event) => selectDevice(event.target.value as DeviceProfileId)}>{Object.values(DEVICE_PROFILES).map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label><label>Glyph family<select value={family} onChange={(event) => setFamily(event.target.value as GlyphFamily)}>{FAMILIES.map((item) => <option key={item} value={item}>{familyLabel(item)}</option>)}</select></label><div className="render-engine-lab__status"><span>Selected family</span><strong>{familyLabel(family)}</strong><small>{familyCount} grapheme{familyCount === 1 ? '' : 's'} in this benchmark</small></div></section>
    <section className="render-engine-lab__panel render-engine-lab__source-panel"><div className="render-engine-lab__panel-heading"><h2>Source and payload diagnostics</h2><div className="render-engine-lab__actions"><button className="button button--secondary" type="button" onClick={() => setSourceText(benchmarkArtwork)}>Load benchmark source</button><button className="button button--secondary" type="button" onClick={applySafeTextRepair}>Preview safe repairs</button></div></div><textarea className="art-studio-artwork-editor" value={sourceText || artwork} onChange={(event) => setSourceText(event.target.value)} aria-label="Render Engine source text" /><div className="render-engine-lab__diagnostics"><span>Code points<strong>{textDiagnostics.codePointCount}</strong></span><span>Graphemes<strong>{textDiagnostics.graphemeCount}</strong></span><span>UTF-16<strong>{textDiagnostics.utf16Length}</strong></span><span>Spaces<strong>{textDiagnostics.ordinarySpaces} / {textDiagnostics.ideographicSpaces}</strong></span><span>Risky<strong>{textDiagnostics.invisibleCharacters + textDiagnostics.unsupportedCharacters}</strong></span><span>Overflow<strong>{textDiagnostics.maximumOverflow} cells</strong></span></div>{textDiagnostics.warnings.map((warning) => <p className="render-engine-lab__warning" key={warning}>⚠ {warning}</p>)}</section>
    <section className="render-engine-lab__profile-bar"><label>Saved profile<select value={activeProfileId ?? ''} onChange={(event) => { const selected = profiles.find((profile) => profile.id === event.target.value); if (selected) loadProfile(selected) }}><option value="">Working defaults</option>{profiles.map((profile) => <option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label><button className="button button--secondary" type="button" onClick={renameProfile} disabled={!activeProfile}>Rename</button><button className="button button--secondary" type="button" onClick={duplicateProfile} disabled={!activeProfile}>Duplicate</button><button className="button button--secondary" type="button" onClick={deleteProfile} disabled={!activeProfile}>Delete</button><button className="button button--secondary" type="button" onClick={exportProfile}>Export JSON</button><label className="render-engine-lab__import">Import JSON<input key={importKey} type="file" accept="application/json" onChange={importProfile} /></label></section>
    <section className={workspaceClasses}>
      <article className="render-engine-lab__panel render-engine-lab__panel--preview"><div className="render-engine-lab__panel-heading"><h2>Forge preview</h2><div className="render-engine-lab__segmented"><button type="button" className={renderMode === 'artwork-only' ? 'is-active' : ''} onClick={() => setRenderMode('artwork-only')}>Artwork only</button><button type="button" className={renderMode === 'chat-simulation' ? 'is-active' : ''} onClick={() => setRenderMode('chat-simulation')}>Chat simulation</button></div></div>{artwork ? <ZoomPanViewport label="Forge preview" zoom={forgeZoom} pan={forgePan} setZoom={setForgeZoom} setPan={setForgePan} className={`render-engine-lab__preview-surface ${previewClasses}`}><KingshotArtRenderer artwork={artwork} labelledBy="render-engine-benchmark-title" calibration={calibration} deviceProfile={deviceId} deviceProfileConfig={deviceProfile} showSimulation={renderMode === 'chat-simulation'} /></ZoomPanViewport> : <div className="render-engine-lab__unavailable"><strong>{benchmark.title}</strong><p>This benchmark has metadata but no approved artwork record in this checkout. Renderer-dependent controls are disabled.</p></div>}<div className="render-engine-lab__preview-actions"><button className="button button--secondary" type="button" onClick={() => setFocusPreview((current) => !current)}>{focusPreview ? 'Exit focus preview' : 'Focus preview'}</button><label>Background<select value={background} onChange={(event) => setBackground(event.target.value as typeof background)}><option value="dark">Dark</option><option value="light">Light</option><option value="checker">Checkerboard</option></select></label><label><input type="checkbox" checked={showGrid} onChange={(event) => setShowGrid(event.target.checked)} /> Cell grid</label><label><input type="checkbox" checked={showGuides} onChange={(event) => setShowGuides(event.target.checked)} /> Guides</label></div></article>
      <article className="render-engine-lab__panel render-engine-lab__panel--reference"><div className="render-engine-lab__panel-heading"><h2>Reference comparison</h2>{referenceName && <button type="button" className="render-engine-lab__text-button" onClick={removeReference}>Remove {referenceName}</button>}</div>{referenceUrl ? <ZoomPanViewport label="Reference screenshot" zoom={referenceZoom} pan={referencePan} setZoom={setReferenceZoom} setPan={setReferencePan} className="render-engine-lab__reference-surface"><img className="render-engine-lab__reference-image" src={referenceUrl} alt="Local reference screenshot" style={{ transform: `translate(${referenceAlignment.x}px, ${referenceAlignment.y}px) scale(${referenceAlignment.scale}) rotate(${referenceAlignment.rotation}deg)`, opacity: referenceAlignment.opacity, mixBlendMode: comparisonMode === 'difference' ? 'difference' : 'normal' }} />{comparisonMode === 'overlay' && artwork && <div className="render-engine-lab__overlay-render"><KingshotArtRenderer artwork={artwork} compact calibration={calibration} deviceProfile={deviceId} deviceProfileConfig={deviceProfile} /></div>}</ZoomPanViewport> : <label className="render-engine-lab__upload">Choose a local image<input key={importKey} type="file" accept="image/*" onChange={selectReference} /></label>}<div className="render-engine-lab__comparison-controls"><button className={comparisonMode === 'side-by-side' ? 'is-active' : ''} type="button" onClick={() => setComparisonMode('side-by-side')}>Side-by-side</button><button className={comparisonMode === 'overlay' ? 'is-active' : ''} type="button" onClick={() => setComparisonMode('overlay')}>Overlay</button><button className={comparisonMode === 'difference' ? 'is-active' : ''} type="button" onClick={() => setComparisonMode('difference')}>Difference view</button><label>Opacity <output>{Math.round(referenceAlignment.opacity * 100)}%</output><input type="range" min="0" max="1" step=".05" value={referenceAlignment.opacity} onChange={(event) => updateAlignment('opacity', event.target.value)} /></label></div></article>
    </section>
    <section className="render-engine-lab__inspector"><article className="render-engine-lab__panel"><div className="render-engine-lab__panel-heading"><h2>Calibration inspector</h2><button className="render-engine-lab__text-button" type="button" onClick={resetFamily} disabled={!familyChanged}>Reset {familyLabel(family)}</button></div>{!artwork && <p className="render-engine-lab__notice">Controls are unavailable because this benchmark has no artwork record.</p>}{artwork && familyCount === 0 && <p className="render-engine-lab__notice">Not present in this benchmark. Select a family with a positive count to see a live effect.</p>}<div className="render-engine-lab__controls">{([['glyphScale', 'Glyph scale', .5, 1.5, .01, ''], ['horizontalScale', 'Horizontal scale', .5, 1.5, .01, ''], ['verticalScale', 'Vertical scale', .5, 1.5, .01, ''], ['baselineOffset', 'Baseline offset', -6, 6, 1, ' px'], ['fontWeight', 'Font weight', 300, 900, 100, ''] ] as const).map(([field, label, min, max, step, unit]) => <label key={field}><span>{label}<output>{calibration[family][field]}{unit}{JSON.stringify(calibration[family][field]) !== JSON.stringify(DEFAULT_CALIBRATION[family][field]) ? ' · changed' : ''}</output></span><input type="range" min={min} max={max} step={step} value={calibration[family][field]} onChange={(event) => updateCalibration(field, event.target.value)} disabled={calibrationControlsDisabled} /></label>)}</div><button className="button button--secondary" type="button" onClick={resetAllCalibration} disabled={!hasCalibrationChanges}>Reset all glyph calibration</button></article>
      <article className="render-engine-lab__panel"><h2>Device overrides</h2><p>Optional local overrides for the selected device profile.</p><div className="render-engine-lab__controls">{([['cellWidth', 'Cell width', 6, 24, 1, ' px'], ['cellHeight', 'Cell height', 10, 32, 1, ' px'], ['gridFontSize', 'Grid font size', 8, 28, 1, ' px'], ['chatBubbleWidth', 'Bubble width', 240, 760, 10, ' px']] as const).map(([field, label, min, max, step, unit]) => <label key={field}><span>{label}<output>{deviceProfile[field]}{unit}</output></span><input type="range" min={min} max={max} step={step} value={deviceProfile[field]} onChange={(event) => updateDevice(field, event.target.value)} /></label>)}</div><button className="button button--secondary" type="button" onClick={resetDeviceOverrides} disabled={!hasDeviceChanges}>Reset device profile overrides</button><button className="button button--secondary" type="button" onClick={resetSession} disabled={!hasWorkingChanges}>Reset entire working session</button></article>
      <article className="render-engine-lab__panel"><h2>Alignment</h2><p>Manual visual alignment only. No automatic matching or score is produced.</p><div className="render-engine-lab__controls">{([['x', 'Horizontal offset', -500, 500, 1, ' px'], ['y', 'Vertical offset', -500, 500, 1, ' px'], ['scale', 'Reference scale', .5, 2, .01, '×'], ['rotation', 'Rotation', -5, 5, .5, '°']] as const).map(([field, label, min, max, step, unit]) => <label key={field}><span>{label}<output>{referenceAlignment[field]}{unit}</output></span><input type="range" min={min} max={max} step={step} value={referenceAlignment[field]} onChange={(event) => updateAlignment(field, event.target.value)} disabled={!referenceUrl} /></label>)}</div><button className="button button--secondary" type="button" onClick={resetAlignment} disabled={!referenceUrl}>Reset alignment</button><h3>Diagnostics</h3><div className="render-engine-lab__diagnostics"><span>Grid<strong>{analysis.widestLine} × {analysis.lineCount}</strong></span><span>Graphemes<strong>{analysis.graphemeCount}</strong></span><span>Renderer<strong>Fixed cell grid</strong></span><span>Family<strong>{familyLabel(family)} · {familyCount}</strong></span><span>Device<strong>{deviceProfile.label}</strong></span><span>Overrides<strong>{Object.keys(deviceOverrides).length + Object.keys(calibration).filter((key) => JSON.stringify(calibration[key as GlyphFamily]) !== JSON.stringify(DEFAULT_CALIBRATION[key as GlyphFamily])).length}</strong></span></div>{analysis.warnings.map((warning) => <p className="render-engine-lab__warning" key={warning}>⚠ {warning}</p>)}</article>
    </section>
    <section className="render-engine-lab__panel render-engine-lab__metadata-panel"><h2 id="render-engine-benchmark-title">Benchmark metadata</h2><dl className="render-engine-lab__metadata"><div><dt>Expected class</dt><dd>{benchmark.expectedArtworkClass}</dd></div><div><dt>Expected renderer</dt><dd>{benchmark.expectedRenderer}</dd></div><div><dt>Validation</dt><dd>{benchmark.validationStatus}</dd></div><div><dt>Target profile</dt><dd>{benchmark.targetDeviceProfile}</dd></div></dl><p>{benchmark.notes}</p></section>
  </main>
}
