import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { useRole } from '../context/RoleContext'
import { getRecruitmentMetrics } from '../services/contributorApplicationService'
import { APP_VERSION } from '../config/release'

const cards = [['Platform status', `Version ${APP_VERSION}`, 'Deployment status is not inferred locally.'], ['Content operations', 'Available', 'Dataset catalogue and Verification Centre are implemented; import, publish and history remain partial/planned.'], ['Player operations', 'Partial', 'Gift Redemption, Player Identity and User Management foundations exist behind server authorization.'], ['Community operations', 'Available', 'Community Art moderation and the contributor application review foundation are capability-gated.'], ['Security and governance', 'Partial', 'Multi-role capability reads and audited identity/recruitment mutations exist; unified Audit Log remains planned.'], ['Responsive validation', 'Pending', 'Authenticated desktop, tablet and mobile validation is still required for this release.']] as const

export default function OperationsDashboardPage() {
  const { hasPermission } = useRole()
  const [metrics, setMetrics] = useState<Record<string, number> | null>(null)
  useEffect(() => { if (hasPermission('applications.read')) void getRecruitmentMetrics().then(setMetrics).catch(() => setMetrics(null)) }, [hasPermission])
  return <main className="workspace-home"><header className="workspace-home__header"><p className="eyebrow">Forge Operations Centre</p><h1>Operate the Forge with confidence.</h1><p>Actionable status from implemented platform surfaces, with unknowns called out instead of invented metrics.</p></header><section className="workspace-home__section" aria-labelledby="operations-status"><div className="workspace-home__section-heading"><div><p className="eyebrow">Operational overview</p><h2 id="operations-status">Current release signals</h2></div><span className="status-badge">In development</span></div><div className="workspace-home__grid">{cards.map(([label, value, detail]) => <article className="workspace-home__card" key={label}><span aria-hidden="true">{value === 'Available' ? '●' : value === 'Partial' ? '◐' : '○'}</span><div><h3>{label}</h3><p><strong>{value}</strong> — {detail}</p></div></article>)}</div></section>{hasPermission('applications.read') && <section className="workspace-home__section"><div className="workspace-home__section-heading"><div><p className="eyebrow">Community operations</p><h2>Contributor recruitment</h2></div><Link className="button button--secondary" to="/operations/applications">Open applications</Link></div>{metrics ? <div className="workspace-home__grid">{[['Submitted', 'submitted'], ['Under review', 'under_review'], ['Awaiting applicant', 'more_information_requested'], ['Accepted/onboarding', 'onboarding'], ['Active', 'active']].map(([label, key]) => <article className="workspace-home__card" key={key}><div><h3>{label}</h3><p><strong>{metrics[key] ?? 0}</strong> current applications</p></div></article>)}</div> : <p>Recruitment metrics are unavailable until the Operations API responds.</p>}</section>}<section className="workspace-home__note"><strong>Access is server-authorized.</strong><span>{hasPermission('users.read') ? <Link to="/operations/users">User Management</Link> : 'User Management'} and {hasPermission('applications.read') ? <Link to="/operations/applications">contributor applications</Link> : 'contributor applications'} require their own capabilities and audit events.</span></section></main>
}
