import type { GuideRegistryEntry } from './guideTypes'

export const guideRegistry: GuideRegistryEntry[] = [
  {
    slug: 'kingshot-heroes-gen1-gen6-role-tier-reference',
    path: '/guides/kingshot-heroes-gen1-gen6-role-tier-reference',
    title: 'Kingshot Heroes Gen 1–6: Role, Tier & F2P Reference',
    shortTitle: 'Heroes Gen 1–6',
    summary: 'Compare the supplied 27-hero Gen 1–6 roster by verified identity fields and clearly separated editorial Rally, Garrison, Bear and Joiner tiers.',
    icon: '🦸',
    type: 'Hero guide',
    tags: ['heroes', 'Generation 1', 'Generation 6', 'tier list', 'rally', 'garrison', 'Bear Hunt', 'joiner', 'F2P', 'Infantry', 'Cavalry', 'Archer'],
  },
  {
    slug: 'kingshot-kvk-preparation-scoring-guide',
    path: '/guides/kingshot-kvk-preparation-scoring-guide',
    title: 'Kingshot KvK Preparation: Complete 5-Day Scoring Reference',
    shortTitle: 'KvK Prep Scoring',
    summary: 'Use all 32 supplied KvK Preparation scoring rows across five days, with repeated-resource opportunities and explicit source-confidence boundaries.',
    icon: '📊',
    type: 'Event guide',
    tags: ['KvK', 'Kingdom of Power', 'prep', 'scoring', 'Truegold', 'Charms', 'Mithril', 'Forgehammer', 'Hero Roulette', 'troops', 'Intel Missions', 'resource management'],
  },
  {
    slug: 'kingshot-building-upgrade-cost-time-guide',
    path: '/guides/kingshot-building-upgrade-cost-time-guide',
    title: 'Kingshot Buildings: Lv.1–30 Upgrade Cost & Time Guide',
    shortTitle: 'Building Progression',
    summary: 'Plan Town Center, War Academy, Barracks, Infirmary and Storehouse upgrades from Lv.1 to Lv.30 with source-governed costs and raw build times.',
    icon: '🏰',
    type: 'System guide',
    tags: ['buildings', 'Town Center', 'War Academy', 'Barracks', 'Infirmary', 'Storehouse', 'Lv.30', 'Building Planner', 'resources', 'build time', 'KvK', 'Alliance Brawl'],
  },
  {
    slug: 'kingshot-troop-training-t1-t5-cost-time-guide',
    path: '/guides/kingshot-troop-training-t1-t5-cost-time-guide',
    title: 'Kingshot Troop Training: T1–T5 Cost, Time & Event-Point Guide',
    shortTitle: 'Troop Training',
    summary: 'Compare the supplied estimated T1–T5 Infantry, Lancer and Marksman costs, training times and calculator-default event points.',
    icon: '🪖',
    type: 'System guide',
    tags: ['troops', 'troop training', 'T1', 'T5', 'Infantry', 'Lancer', 'Marksman', 'training time', 'KvK', 'HoG', 'TSG', 'resource management'],
  },
  {
    slug: 'kingshot-hero-xp-shard-progression-guide',
    path: '/guides/kingshot-hero-xp-shard-progression-guide',
    title: 'Kingshot Hero Progression: Lv.1–80 XP & Shard Cost Guide',
    shortTitle: 'Hero Progression',
    summary: 'Plan hero levels 1–80 with the supplied XP curve, deployment-capacity confidence boundary and clearly separated shard estimates.',
    icon: '📈',
    type: 'System guide',
    tags: ['heroes', 'Hero XP', 'hero shards', 'Lv.80', 'star-up', 'deployment capacity', 'F2P', 'progression', 'resource management'],
  },
  {
    slug: 'kingshot-war-academy-research-truegold-dust-guide',
    path: '/guides/kingshot-war-academy-research-truegold-dust-guide',
    title: 'Kingshot War Academy: Research, Truegold Dust & T11 Guide',
    shortTitle: 'War Academy',
    summary: 'Plan the supplied 30-technology War Academy tree with troop-specific research, Truegold Dust, resources, time and T11 unlock paths.',
    icon: '🧪',
    type: 'System guide',
    tags: ['War Academy', 'Truegold Dust', 'T11', 'research', 'Infantry', 'Cavalry', 'Archer', 'troops', 'KvK', 'Alliance Brawl', 'resource management'],
  },
  {
    slug: 'kingshot-vip-1-12-xp-gem-cost-guide',
    path: '/guides/kingshot-vip-1-12-xp-gem-cost-guide',
    title: 'Kingshot VIP 1–12: VIP XP & Gem-Equivalent Cost Guide',
    shortTitle: 'VIP Progression',
    summary: 'Plan VIP 1–12 with the supplied VIP XP requirements, exact 1:2 Gem conversion and an explicit boundary around unsupported benefits.',
    icon: '👑',
    type: 'System guide',
    tags: ['VIP', 'VIP 12', 'VIP XP', 'Gems', 'progression', 'gem budgeting', 'resource planning'],
  },
  {
    slug: 'kingshot-governor-charms-upgrade-cost-guide',
    path: '/guides/kingshot-governor-charms-upgrade-cost-guide',
    title: 'Kingshot Governor Charms: Lv.1–22 Cost, Stats & Power Guide',
    shortTitle: 'Governor Charms',
    summary: 'Plan all 22 Governor Charm levels with Charm Guides, Charm Designs, cumulative stat milestones, power gains and source confidence.',
    icon: '✨',
    type: 'System guide',
    tags: ['Governor Charms', 'Charm Guides', 'Charm Designs', 'Lv.22', 'stats', 'power', 'F2P', 'Alliance Brawl', 'KvK', 'resource management'],
  },
  {
    slug: 'kingshot-governor-gear-upgrade-cost-guide',
    path: '/guides/kingshot-governor-gear-upgrade-cost-guide',
    title: 'Kingshot Governor Gear: Complete Upgrade Cost & Progression Guide',
    shortTitle: 'Governor Gear',
    summary: 'Plan all 58 Governor Gear steps from Green to Red T6 with Satin, Gilded Threads, Artisan’s Vision, stat milestones, power and confidence.',
    icon: '⚒️',
    type: 'System guide',
    tags: ['Governor Gear', 'Satin', 'Gilded Threads', 'Artisan’s Vision', 'Red T6', 'gear', 'F2P', 'Alliance Brawl', 'KvK', 'resource management', 'power'],
  },
  {
    slug: 'kingshot-truegold-tempered-truegold-building-guide',
    path: '/guides/kingshot-truegold-tempered-truegold-building-guide',
    title: 'Kingshot Truegold & Tempered Truegold: TG1–TG8 Building Cost Guide',
    shortTitle: 'Truegold Progression',
    summary: 'Plan TG1–TG8 building costs with governed Truegold and Tempered Truegold requirements, confidence notes and connected event timing.',
    icon: '🔥',
    type: 'System guide',
    tags: ['Truegold', 'Tempered Truegold', 'TG1', 'TG6', 'TG8', 'buildings', 'Building Planner', 'KvK', 'Alliance Brawl', 'resource management', 'F2P'],
  },
  {
    slug: 'kingshot-generation-7-heroes-ava-charles-wee-woo-guide',
    path: '/guides/kingshot-generation-7-heroes-ava-charles-wee-woo-guide',
    title: 'Kingshot Generation 7 Heroes: Ava, Charles & Wee & Woo Skill Guide',
    shortTitle: 'Generation 7 Heroes',
    summary: 'Compare Ava, Charles and Wee & Woo using Forge’s supplied Gen 7 skill verification and editorial review data, with source limits clearly preserved.',
    icon: '🦸',
    type: 'Hero guide',
    tags: ['heroes', 'Generation 7', 'Ava', 'Charles', 'Wee & Woo', 'skill guide', 'damage amplification', 'defence', 'rallies', 'PvP'],
  },
  {
    slug: 'kingshot-masters-master-academy-guide',
    path: '/guides/kingshot-masters-master-academy-guide',
    title: 'Kingshot Masters: Master Academy, Affinity & Upgrade Priority Guide',
    shortTitle: 'Masters',
    summary: 'Compare all six current Masters, their Affinity bonuses, F2P priorities, Manuscript investment and event specialisations.',
    icon: '📜',
    type: 'System guide',
    tags: ['Masters', 'Master Academy', 'Affinity', 'Manuscripts', 'F2P', 'Pan', 'Valora', 'Roman', 'Cassia', 'Guinevere', 'Wilson', 'Bear Hunt', 'Swordland', 'Alliance events'],
  },
  {
    slug: 'kingshot-oasis-island-player-guide',
    path: '/guides/kingshot-oasis-island-player-guide',
    title: 'Kingshot Oasis Island: Complete Player & Progression Guide',
    shortTitle: 'Oasis Island',
    summary: 'Plan Water Essence, Prosperity, Fountain and Reservoir progression, cactus clearing, treasure routes, building buffs and Golden Sunset.',
    icon: '🌴',
    type: 'System guide',
    tags: ['Oasis Island', 'Water Essence', 'Prosperity', 'Fountain of Life', 'Reservoir', 'F2P', 'buildings', 'buffs', 'route planning', 'Golden Sunset'],
  },
  {
    slug: 'kingshot-kingdom-of-power-kvk-guide',
    path: '/guides/kingshot-kingdom-of-power-kvk-guide',
    title: 'Kingshot Kingdom of Power (KvK): Complete Prep & Battle Guide',
    shortTitle: 'Kingdom of Power (KvK)',
    summary: 'Plan matchmaking, five-day Prep, cross-kingdom battle, Castle and Turret tactics, F2P contribution, whale coordination and Field Triage.',
    icon: '👑',
    type: 'Event guide',
    tags: ['KvK', 'cross-server', 'prep', 'Castle Battle', 'F2P', 'whales', 'Truegold', 'healing'],
  },
  {
    slug: 'kingshot-swordland-showdown-summit-league-guide',
    path: '/guides/kingshot-swordland-showdown-summit-league-guide',
    title: 'Kingshot Swordland: Showdown & Summit League Guide',
    shortTitle: 'Swordland',
    summary: 'Master the one-hour battlefield, Relic Points, Bell Tower, Royal Stables, Swordshrine, role assignments, F2P utility and whale rally tactics.',
    icon: '⚔️',
    type: 'Event guide',
    tags: ['Swordland', 'cross-server', 'PvP', 'alliance', 'Relic Points', 'garrison', 'F2P', 'rallies'],
  },
  {
    slug: 'kingshot-alliance-brawl-event-guide',
    path: '/guides/kingshot-alliance-brawl-event-guide',
    title: 'Kingshot Alliance Brawl: Complete 13-Horn Strategy Guide',
    shortTitle: 'Alliance Brawl',
    summary: 'Plan all six stages, conserve resources for the four-Horn finale, double-dip overlapping events and balance Brawl spending against KvK.',
    icon: '📯',
    type: 'Event guide',
    tags: ['Alliance Brawl', 'alliance', 'Horns', 'resource management', 'F2P', 'whales', 'KvK', 'event stacking'],
  },
  {
    slug: 'kingshot-champagne-fair-guide',
    path: '/guides/kingshot-champagne-fair-guide',
    title: 'Kingshot Champagne Fair: Voucher Exchange & Shop Guide',
    shortTitle: 'Champagne Fair',
    summary: 'Convert surplus shards, widgets and skill books into persistent Fair Vouchers, then spend them on high-value progression materials.',
    icon: '🥂',
    type: 'Event guide',
    tags: ['Champagne Fair', 'vouchers', 'Mithril', 'hero widgets', 'hero shards', 'F2P', 'economy', 'resource management'],
  },
  {
    slug: 'kingshot-mystic-divination-event-guide',
    path: '/guides/kingshot-mystic-divination-event-guide',
    title: 'Kingshot Mystic Divination: Fortune Token Strategy Guide',
    shortTitle: 'Mystic Divination',
    summary: 'Use the five-flip reset strategy, evaluate board quality, stack multipliers and hoard persistent Fortune Tokens for milestone runs.',
    icon: '🔮',
    type: 'Event guide',
    tags: ['Mystic Divination', 'Fortune Tokens', 'probability', 'F2P', 'hoarding', 'Truegold', 'multipliers', 'rewards'],
  },
  {
    slug: 'kingshot-fishing-tournament-guide',
    path: '/guides/kingshot-fishing-tournament-guide',
    title: 'Kingshot Fishing Tournament: Complete F2P & Leaderboard Guide',
    shortTitle: 'Fishing Tournament',
    summary: 'Upgrade Line, Hook and Sinker, target high-value catches, manage Prospector Maps and build a seasonal hoard for leaderboard pushes.',
    icon: '🎣',
    type: 'Event guide',
    tags: ['Fishing Tournament', 'fishing', 'F2P', 'leaderboard', 'seasonal', 'gear', 'minigame', 'rewards'],
  },
  {
    slug: 'kingshot-twin-star-adventure-guide',
    path: '/guides/kingshot-twin-star-adventure-guide',
    title: 'Kingshot Twin Star Adventure: Dice, Team & Polar Shop Guide',
    shortTitle: 'Twin Star Adventure',
    summary: 'Coordinate a three-player team, use Crystal Dice precisely, level board tiles, damage the Ice Megalodon and spend Twinstar Coins efficiently.',
    icon: '❄️',
    type: 'Event guide',
    tags: ['Twin Star Adventure', 'team', 'dice', 'Twinstar Coins', 'Ice Megalodon', 'F2P', 'board', 'Polar Shop'],
  },
  {
    slug: 'kingshot-viking-vengeance-event-guide',
    path: '/guides/kingshot-viking-vengeance-event-guide',
    title: 'Kingshot Viking Vengeance: The Complete Alliance Guide',
    shortTitle: 'Viking Vengeance',
    summary: 'Master all 20 waves, reinforcement scoring, HQ transitions, late-wave defence and alliance squad tactics.',
    icon: '🛡️',
    type: 'Event guide',
    tags: ['Viking Vengeance', 'alliance', '20 waves', 'reinforcements', 'HQ', 'F2P', 'Guard Station'],
  },
  {
    slug: 'flamedragon-tyrant-event-guide',
    path: '/guides/flamedragon-tyrant-event-guide',
    title: 'Kingshot Flamedragon Tyrant: The Complete Event Guide',
    shortTitle: 'Flamedragon Tyrant',
    summary: 'Plan the event timeline, battlefield safety, F2P tasks, Palace strategy, Aeries, healing and rewards.',
    icon: '🐉',
    type: 'Event guide',
    tags: ['Flamedragon Tyrant', 'alliance', 'Palace', 'Aeries', 'F2P', 'PvP', 'healing'],
  },
  {
    slug: 'kingshot-generation-6-heroes-yang-sophia-triton-guide',
    path: '/guides/kingshot-generation-6-heroes-yang-sophia-triton-guide',
    title: 'Kingshot Generation 6 Heroes: Yang, Sophia & Triton',
    shortTitle: 'Generation 6 Heroes',
    summary: 'Compare Yang, Sophia and Triton, including acquisition, roles, build order, rally mechanics and F2P priorities.',
    icon: '🦸',
    type: 'Hero guide',
    tags: ['heroes', 'Generation 6', 'Yang', 'Sophia', 'Triton', 'F2P', 'rallies'],
  },
]

export const allGuideTags = [...new Set(guideRegistry.flatMap((guide) => guide.tags))]
  .sort((left, right) => left.localeCompare(right))
