import type { GuideRegistryEntry } from './guideTypes'

export const guideRegistry: GuideRegistryEntry[] = [
  {
    slug: 'kingshot-kingdom-of-power-kvk-guide',
    path: '/guides/kingshot-kingdom-of-power-kvk-guide',
    title: 'Kingshot Kingdom of Power (KvK): Complete Prep & Battle Guide',
    shortTitle: 'Kingdom of Power (KvK)',
    summary: 'Plan matchmaking, five-day Prep, cross-kingdom battle, Castle and Turret tactics, F2P contribution, whale coordination and Field Triage.',
    icon: '👑',
    type: 'Event guide',
    tags: ['KvK', 'cross-server', 'prep', 'Castle Battle', 'F2P', 'whales', 'Truegold', 'healing'],
  },
  {
    slug: 'kingshot-swordland-showdown-summit-league-guide',
    path: '/guides/kingshot-swordland-showdown-summit-league-guide',
    title: 'Kingshot Swordland: Showdown & Summit League Guide',
    shortTitle: 'Swordland',
    summary: 'Master the one-hour battlefield, Relic Points, Bell Tower, Royal Stables, Swordshrine, role assignments, F2P utility and whale rally tactics.',
    icon: '⚔️',
    type: 'Event guide',
    tags: ['Swordland', 'cross-server', 'PvP', 'alliance', 'Relic Points', 'garrison', 'F2P', 'rallies'],
  },
  {
    slug: 'kingshot-alliance-brawl-event-guide',
    path: '/guides/kingshot-alliance-brawl-event-guide',
    title: 'Kingshot Alliance Brawl: Complete 13-Horn Strategy Guide',
    shortTitle: 'Alliance Brawl',
    summary: 'Plan all six stages, conserve resources for the four-Horn finale, double-dip overlapping events and balance Brawl spending against KvK.',
    icon: '📯',
    type: 'Event guide',
    tags: ['Alliance Brawl', 'alliance', 'Horns', 'resource management', 'F2P', 'whales', 'KvK', 'event stacking'],
  },
  {
    slug: 'kingshot-champagne-fair-guide',
    path: '/guides/kingshot-champagne-fair-guide',
    title: 'Kingshot Champagne Fair: Voucher Exchange & Shop Guide',
    shortTitle: 'Champagne Fair',
    summary: 'Convert surplus shards, widgets and skill books into persistent Fair Vouchers, then spend them on high-value progression materials.',
    icon: '🥂',
    type: 'Event guide',
    tags: ['Champagne Fair', 'vouchers', 'Mithril', 'hero widgets', 'hero shards', 'F2P', 'economy', 'resource management'],
  },
  {
    slug: 'kingshot-mystic-divination-event-guide',
    path: '/guides/kingshot-mystic-divination-event-guide',
    title: 'Kingshot Mystic Divination: Fortune Token Strategy Guide',
    shortTitle: 'Mystic Divination',
    summary: 'Use the five-flip reset strategy, evaluate board quality, stack multipliers and hoard persistent Fortune Tokens for milestone runs.',
    icon: '🔮',
    type: 'Event guide',
    tags: ['Mystic Divination', 'Fortune Tokens', 'probability', 'F2P', 'hoarding', 'Truegold', 'multipliers', 'rewards'],
  },
  {
    slug: 'kingshot-fishing-tournament-guide',
    path: '/guides/kingshot-fishing-tournament-guide',
    title: 'Kingshot Fishing Tournament: Complete F2P & Leaderboard Guide',
    shortTitle: 'Fishing Tournament',
    summary: 'Upgrade Line, Hook and Sinker, target high-value catches, manage Prospector Maps and build a seasonal hoard for leaderboard pushes.',
    icon: '🎣',
    type: 'Event guide',
    tags: ['Fishing Tournament', 'fishing', 'F2P', 'leaderboard', 'seasonal', 'gear', 'minigame', 'rewards'],
  },
  {
    slug: 'kingshot-twin-star-adventure-guide',
    path: '/guides/kingshot-twin-star-adventure-guide',
    title: 'Kingshot Twin Star Adventure: Dice, Team & Polar Shop Guide',
    shortTitle: 'Twin Star Adventure',
    summary: 'Coordinate a three-player team, use Crystal Dice precisely, level board tiles, damage the Ice Megalodon and spend Twinstar Coins efficiently.',
    icon: '❄️',
    type: 'Event guide',
    tags: ['Twin Star Adventure', 'team', 'dice', 'Twinstar Coins', 'Ice Megalodon', 'F2P', 'board', 'Polar Shop'],
  },
  {
    slug: 'kingshot-viking-vengeance-event-guide',
    path: '/guides/kingshot-viking-vengeance-event-guide',
    title: 'Kingshot Viking Vengeance: The Complete Alliance Guide',
    shortTitle: 'Viking Vengeance',
    summary: 'Master all 20 waves, reinforcement scoring, HQ transitions, late-wave defence and alliance squad tactics.',
    icon: '🛡️',
    type: 'Event guide',
    tags: ['Viking Vengeance', 'alliance', '20 waves', 'reinforcements', 'HQ', 'F2P', 'Guard Station'],
  },
  {
    slug: 'flamedragon-tyrant-event-guide',
    path: '/guides/flamedragon-tyrant-event-guide',
    title: 'Kingshot Flamedragon Tyrant: The Complete Event Guide',
    shortTitle: 'Flamedragon Tyrant',
    summary: 'Plan the event timeline, battlefield safety, F2P tasks, Palace strategy, Aeries, healing and rewards.',
    icon: '🐉',
    type: 'Event guide',
    tags: ['Flamedragon Tyrant', 'alliance', 'Palace', 'Aeries', 'F2P', 'PvP', 'healing'],
  },
  {
    slug: 'kingshot-generation-6-heroes-yang-sophia-triton-guide',
    path: '/guides/kingshot-generation-6-heroes-yang-sophia-triton-guide',
    title: 'Kingshot Generation 6 Heroes: Yang, Sophia & Triton',
    shortTitle: 'Generation 6 Heroes',
    summary: 'Compare Yang, Sophia and Triton, including acquisition, roles, build order, rally mechanics and F2P priorities.',
    icon: '🦸',
    type: 'Hero guide',
    tags: ['heroes', 'Generation 6', 'Yang', 'Sophia', 'Triton', 'F2P', 'rallies'],
  },
]

export const allGuideTags = [...new Set(guideRegistry.flatMap((guide) => guide.tags))]
  .sort((left, right) => left.localeCompare(right))
