begin;

create table public.oasis_publication_versions (
  publication_id text primary key,
  publication_version bigint generated by default as identity unique not null,
  schema_version text not null check (schema_version = 'oasis-public-projection-v1'),
  status text not null check (status = 'published'),
  source_fingerprint text not null,
  manifest jsonb not null,
  manifest_hash text not null check (manifest_hash ~ '^[0-9a-f]{64}$'),
  record_count integer not null check (record_count = 55),
  media_count integer not null check (media_count = 111),
  actor_id text not null,
  publication_reason text not null,
  idempotency_key text not null unique,
  rollback_of_publication_id text references public.oasis_publication_versions(publication_id) on delete restrict,
  published_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.oasis_publication_records (
  publication_id text not null references public.oasis_publication_versions(publication_id) on delete restrict,
  record_id text not null,
  public_record jsonb not null,
  primary key (publication_id, record_id),
  check (public_record->>'schemaVersion' = 'oasis-public-projection-v1'),
  check (public_record->>'status' = 'published'),
  check (public_record->>'id' = record_id),
  check (not public_record ?| array['_meta', 'source', 'sourceUrl', 'sourceText', 'sourceDocument', 'sourceTableIndex', 'verification', 'verificationHistory', 'verificationNotes', 'provenance', 'provenanceNotes', 'knownConflicts', 'privateSourceFilename', 'imageInventory', 'imageFiles', 'imageVariantFiles', 'assetStem', 'repositoryPath', 'filesystemPath'])
);

create table public.oasis_publication_current (
  singleton boolean primary key default true check (singleton),
  publication_id text not null unique references public.oasis_publication_versions(publication_id) on delete restrict,
  activated_at timestamptz not null,
  activated_by text not null
);

create table public.oasis_publication_audits (
  audit_id uuid primary key default gen_random_uuid(),
  publication_id text not null references public.oasis_publication_versions(publication_id) on delete restrict,
  action text not null check (action in ('published', 'rollback_published')),
  actor_id text not null,
  reason text not null,
  previous_publication_id text,
  manifest_hash text not null,
  occurred_at timestamptz not null default now(),
  evidence jsonb not null default '{}'::jsonb
);

create table public.oasis_publication_search_refreshes (
  publication_id text primary key references public.oasis_publication_versions(publication_id) on delete restrict,
  status text not null check (status in ('pending', 'running', 'succeeded', 'failed')) default 'pending',
  attempt_count integer not null default 0,
  error_message text,
  requested_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.oasis_publication_versions enable row level security;
alter table public.oasis_publication_records enable row level security;
alter table public.oasis_publication_current enable row level security;
alter table public.oasis_publication_audits enable row level security;
alter table public.oasis_publication_search_refreshes enable row level security;

revoke all on public.oasis_publication_versions, public.oasis_publication_records,
  public.oasis_publication_current, public.oasis_publication_audits,
  public.oasis_publication_search_refreshes from public, anon, authenticated;
grant select on public.oasis_publication_versions, public.oasis_publication_records,
  public.oasis_publication_current, public.oasis_publication_audits,
  public.oasis_publication_search_refreshes to service_role;

create or replace function public.prevent_oasis_publication_history_mutation()
returns trigger language plpgsql security definer set search_path = pg_catalog as $$
begin
  raise exception '% is append-only; % is not permitted', tg_table_name, tg_op;
end;
$$;
revoke all on function public.prevent_oasis_publication_history_mutation() from public, anon, authenticated;
grant execute on function public.prevent_oasis_publication_history_mutation() to service_role;

create trigger oasis_versions_immutable before update or delete on public.oasis_publication_versions
for each row execute function public.prevent_oasis_publication_history_mutation();
create trigger oasis_records_immutable before update or delete on public.oasis_publication_records
for each row execute function public.prevent_oasis_publication_history_mutation();
create trigger oasis_audits_immutable before update or delete on public.oasis_publication_audits
for each row execute function public.prevent_oasis_publication_history_mutation();

create or replace function public.publish_oasis_catalogue(
  p_publication_id text,
  p_schema_version text,
  p_source_fingerprint text,
  p_manifest jsonb,
  p_manifest_hash text,
  p_records jsonb,
  p_actor_id text,
  p_reason text,
  p_idempotency_key text,
  p_rollback_of_publication_id text default null
)
returns jsonb language plpgsql security definer set search_path = public, pg_catalog as $$
declare
  existing public.oasis_publication_versions%rowtype;
  previous_id text;
  version_value bigint;
begin
  if current_user not in ('service_role', 'postgres') then raise exception 'Oasis publication is service-role-only.'; end if;
  perform pg_advisory_xact_lock(hashtext('forge-oasis-publication'));
  select * into existing from public.oasis_publication_versions where idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object('publicationId', existing.publication_id, 'publicationVersion', existing.publication_version, 'duplicate', true);
  end if;
  if p_schema_version <> 'oasis-public-projection-v1' then raise exception 'Unsupported Oasis public projection schema.'; end if;
  if p_manifest_hash !~ '^[0-9a-f]{64}$' then raise exception 'Invalid Oasis manifest hash.'; end if;
  if jsonb_typeof(p_records) <> 'array' or jsonb_array_length(p_records) <> 55 then raise exception 'Oasis publication requires exactly 55 public records.'; end if;
  if (p_manifest->>'sourceAssetCount')::integer <> 111 or (p_manifest->>'derivativeAssetCount')::integer <> 111 then raise exception 'Oasis publication requires exactly 111 mapped media assets.'; end if;
  if exists (
    select 1 from jsonb_array_elements(p_records) r
    where r->>'schemaVersion' <> p_schema_version or r->>'status' <> 'published'
      or r ?| array['_meta', 'source', 'sourceUrl', 'sourceText', 'verification', 'provenance', 'privateSourceFilename', 'imageFiles', 'repositoryPath', 'filesystemPath']
  ) then raise exception 'Oasis public records failed the publication boundary.'; end if;
  if (select count(distinct r->>'id') from jsonb_array_elements(p_records) r) <> 55 then raise exception 'Oasis record IDs must be complete and unique.'; end if;
  if p_rollback_of_publication_id is not null and not exists (select 1 from public.oasis_publication_versions where publication_id = p_rollback_of_publication_id) then raise exception 'Rollback source publication does not exist.'; end if;

  select publication_id into previous_id from public.oasis_publication_current where singleton = true for update;
  insert into public.oasis_publication_versions(
    publication_id, schema_version, status, source_fingerprint, manifest, manifest_hash,
    record_count, media_count, actor_id, publication_reason, idempotency_key,
    rollback_of_publication_id
  ) values (
    p_publication_id, p_schema_version, 'published', p_source_fingerprint, p_manifest,
    p_manifest_hash, 55, 111, p_actor_id, p_reason, p_idempotency_key,
    p_rollback_of_publication_id
  ) returning publication_version into version_value;
  insert into public.oasis_publication_records(publication_id, record_id, public_record)
    select p_publication_id, r->>'id', r || jsonb_build_object('publicationId', p_publication_id, 'publicationVersion', version_value)
    from jsonb_array_elements(p_records) r;
  insert into public.oasis_publication_search_refreshes(publication_id, status) values (p_publication_id, 'pending');
  insert into public.oasis_publication_audits(publication_id, action, actor_id, reason, previous_publication_id, manifest_hash, evidence)
    values (p_publication_id, case when p_rollback_of_publication_id is null then 'published' else 'rollback_published' end,
      p_actor_id, p_reason, previous_id, p_manifest_hash,
      jsonb_build_object('recordCount', 55, 'mediaCount', 111, 'sourceFingerprint', p_source_fingerprint, 'rollbackOf', p_rollback_of_publication_id));
  insert into public.oasis_publication_current(singleton, publication_id, activated_at, activated_by)
    values (true, p_publication_id, now(), p_actor_id)
    on conflict (singleton) do update set publication_id = excluded.publication_id, activated_at = excluded.activated_at, activated_by = excluded.activated_by;
  return jsonb_build_object('publicationId', p_publication_id, 'publicationVersion', version_value, 'duplicate', false, 'previousPublicationId', previous_id);
end;
$$;
revoke all on function public.publish_oasis_catalogue(text, text, text, jsonb, text, jsonb, text, text, text, text) from public, anon, authenticated;
grant execute on function public.publish_oasis_catalogue(text, text, text, jsonb, text, jsonb, text, text, text, text) to service_role;

comment on table public.oasis_publication_versions is 'OASIS-001A-PUB immutable publication history. Applying this migration does not publish a catalogue.';
comment on function public.publish_oasis_catalogue(text, text, text, jsonb, text, jsonb, text, text, text, text) is 'Creates and atomically activates a new immutable Oasis publication. Rollback creates a new publication; it never mutates history.';

commit;
